### ISSUE TITLE
I want to ask some questions about log mods.

### ISSUE THREAD

**Issue by NakiriFox** [mattymatty97/LTC_AsyncLoggers#7]
①What is the difference between AsyncLoggers_Filter and LessLogs?
②Should I uninstall LessLogs to use AsyncLoggers_Filter？
![image](https://github.com/user-attachments/assets/79bcf081-7043-4219-9732-e7d0a2fd6aa2)
![image](https://github.com/user-attachments/assets/4ad0c599-914a-449a-ac66-10a2e5461e09)
③Do I need to make any changes to the log mod I installed?

**Comment by mattymatty97** [comment]
while `LessLogsv and `AsyncLoggers Filter` are doing virtually the same thing
`LessLogs` uses StackTraces ( StackFrames to be precise ) which are notoriously slow ( a lot! ) to detect what mod is generating the current log. 
multiplied for all the logs in the game it's an enormous overhead.

`AsyncLoggers Filter` works by tracking logs using the pre-existing LogSource parameter. and allows for filtering them based on the visualized name instead of detecting the assembly.

now i have not ran any performance comparisons yet but the theory tips towards my mod being more performant

as a footnote i'll precise that neither `LessLogs` nor `AsyncLoggers Filter` will show any performance boost if you have the base `AsyncLoggers` installed, but are only usefull to generate "Cleaner" logs.

**Comment by NakiriFox** [comment]
Thank you for your response, I will set all the [Noneow mod to write logs] to False in AsyncLoggers.Filter.cfg and uninstall LessLog :)

**Comment by mattymatty97** [comment]
if all you want is to completely disable login, you should not use this mod and instead lookat the BepInEx.cfg

this mod is intended to be used to target specific mods

and while i give the option to completely suppress a mod it's better to at least allow Error and Fatal logs

**Comment by NakiriFox** [comment]
In fact, I have already closed all logs on BepInEx.cfg.
I will only do this after ensuring that my modpack is no bug.
